# Generated by Django 3.0.2 on 2020-01-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, null=True)),
                ('bulb_time', models.IntegerField(default=0)),
                ('exposure', models.CharField(choices=[('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('13', '13'), ('10', '10'), ('8', '8'), ('6', '6'), ('5', '5'), ('4', '4'), ('3.2', '3.2'), ('2.5', '2.5'), ('2', '2'), ('1.6', '1.6'), ('1.3', '1.3'), ('1', '1'), ('0.8', '0.8'), ('0.6', '0.6'), ('0.5', '0.5'), ('0.4', '0.4'), ('0.3', '0.3'), ('1/4', '1/4'), ('1/5', '1/5'), ('1/6', '1/6'), ('1/8', '1/8'), ('1/10', '1/10'), ('1/13', '1/13'), ('1/15', '1/15'), ('1/20', '1/20'), ('1/25', '1/25'), ('1/30', '1/30'), ('1/40', '1/40'), ('1/50', '1/50'), ('1/60', '1/60'), ('1/80', '1/80'), ('1/100', '1/100'), ('1/4000', '1/4000')], default='0.4', max_length=6, null=True)),
                ('aperture', models.CharField(choices=[('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.6', '5.6'), ('6.3', '6.3'), ('7.1', '7.1'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('13', '13'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('22', '22')], default='11', max_length=3)),
                ('iso', models.CharField(choices=[('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1600', '1600'), ('3200', '3200'), ('6400', '6400'), ('12800', '12800'), ('25600', '25600')], max_length=5)),
                ('image_format', models.CharField(choices=[('Large Fine JPEG', 'Large Fine JPEG'), ('Large Normal JPEG', 'Large Normal JPEG'), ('Medium Fine JPEG', 'Medium Fine JPEG'), ('Medium Normal JPEG', 'Medium Normal JPEG'), ('Small Fine JPEG', 'Small Fine JPEG'), ('Small Normal JPEG', 'Small Normal JPEG'), ('Small JPEG ', 'Kleineres JPEG'), ('RAW + Large Fine JPEG ', 'RAW + Large Fine JPEG'), ('RAW  ', 'RAW')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CaptureFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, null=True)),
                ('path', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('0', 'Preview'), ('1', 'Focus'), ('2', 'Full')], max_length=100, null=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.CaptureConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeats', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.CaptureConfig')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.CaptureFlow')),
            ],
        ),
    ]
