# Generated by Django 3.0.2 on 2020-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureconfig',
            name='image_format',
            field=models.CharField(choices=[('Large Fine JPEG', 'Large Fine JPEG'), ('Large Normal JPEG', 'Large Normal JPEG'), ('Medium Fine JPEG', 'Medium Fine JPEG'), ('Medium Normal JPEG', 'Medium Normal JPEG'), ('Small Fine JPEG', 'Small Fine JPEG'), ('Small Normal JPEG', 'Small Normal JPEG'), ('Small JPEG', 'Small JPEG'), ('RAW + Large Fine JPEG ', 'RAW + Large Fine JPEG'), ('RAW  ', 'RAW')], max_length=25),
        ),
    ]
