# Generated by Django 3.0.2 on 2020-01-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20200111_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
