# Generated by Django 3.0.2 on 2020-01-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_auto_20200116_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureconfig',
            name='aperture',
            field=models.IntegerField(choices=[('0', '4'), ('1', '4.5'), ('2', '5'), ('3', '5.6'), ('4', '6.3'), ('5', '7.1'), ('6', '8'), ('7', '9'), ('8', '10'), ('9', '11'), ('10', '13'), ('11', '14'), ('12', '16'), ('13', '18'), ('14', '20'), ('15', '22')], default='9'),
        ),
        migrations.AlterField(
            model_name='captureconfig',
            name='exposure',
            field=models.IntegerField(choices=[('9', '5'), ('10', '4'), ('11', '3.2'), ('12', '2.5'), ('13', '2'), ('14', '1.6'), ('15', '1.3'), ('16', '1'), ('17', '0.8'), ('18', '0.6'), ('19', '0.5'), ('20', '0.4'), ('21', '0.3'), ('22', '1/4'), ('23', '1/5'), ('24', '1/6'), ('25', '1/8'), ('26', '1/10'), ('27', '1/13'), ('28', '1/15'), ('29', '1/20'), ('30', '1/25'), ('31', '1/30'), ('32', '1/40'), ('33', '1/50'), ('34', '1/60'), ('35', '1/80'), ('36', '1/100'), ('43', '1/500'), ('46', '1/1000')], default='28', null=True),
        ),
        migrations.AlterField(
            model_name='captureconfig',
            name='image_format',
            field=models.IntegerField(choices=[('0', 'Large Fine JPEG'), ('1', 'Large Normal JPEG'), ('2', 'Medium Fine JPEG'), ('3', 'Medium Normal JPEG'), ('4', 'Small Fine JPEG'), ('5', 'Small Normal JPEG'), ('6', 'Small JPEG'), ('7', 'RAW + Large Fine JPEG'), ('8', 'RAW')]),
        ),
        migrations.AlterField(
            model_name='captureconfig',
            name='iso',
            field=models.IntegerField(choices=[('0', 'Auto'), ('1', '100'), ('2', '200'), ('3', '400'), ('4', '800'), ('5', '1600'), ('6', '3200'), ('7', '6400'), ('8', '12800'), ('9', '25600')]),
        ),
    ]
